name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

 Deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

      - name: Build and push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t $DOCKER_USERNAME/nandobot-go .
          docker push $DOCKER_USERNAME/nandobot-go   

      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.EC2_KEY  }}
            HOSTNAME : ${{ secrets.EC2_HOST  }}
            USER_NAME : ${{ secrets.EC2_USERNAME  }}
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '          
            echo "Deploying..."
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker pull $DOCKER_USERNAME/nandobot-go
            docker stop nandobot-go
            docker rm nandobot-go
            docker run -d --name nandobot-go -v ~/nandobot-go/nandobot.db:/nandobot.db -v ~/nandobot-go/config.json:/config.json -p 8080:8080 $DOCKER_USERNAME/nandobot-go   
            '
      
      
      
      
